export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const FILTER_BY_COLOR = 'FILTER_BY_COLOR';
export const FILTER_BY_SHEET_STYLE = 'FILTER_BY_SHEET_STYLE';
export const FILTER_BY_COVER_MATERIAL = 'FILTER_BY_COVER_MATERIAL';
export const FILTER_BY_AUDIENCE = 'FILTER_BY_AUDIENCE';

export const SORT_BY_LOWEST_PRICE = 'SORT_BY_LOWEST_PRICE';
export const SORT_BY_HIGHEST_PRICE = 'SORT_BY_HIGHEST_PRICE';
export const SORT_BY_POPULAR = 'SORT_BY_POPULAR';
export const SORT_BY_NEW_ARRIVALS = 'SORT_BY_NEW_ARRIVALS';
export const SORT_BY_MOST_REVIEWS = 'SORT_BY_MOST_REVIEWS';
