export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const FETCH_CART = "FETCH_CART";
export const ARE_ALL_FIELDS_SELECTED = "ARE_ALL_FIELDS_SELECTED";

export const DISPLAY_CURRENT_ROUTE = "DISPLAY_CURRENT_ROUTE";

export const SORT_BY = "SORT_BY";

export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";

export const HANDLE_WAYPOINT = "HANDLE_WAYPOINT";
